### ISSUE TITLE
Bridgetownrb returns an error when using {% svg "path" %} in a code piece

### ISSUE THREAD

**Issue by JuanVqz** [ayushn21/bridgetown-svg-inliner#1]
As I said in my blog I wanted to show off  how to install and use this gem in Bridgetown

when I was writing in a markdown file and put the following lines as code blocks, the compiler just breaks down.

```liquid
<!-- Liquid -->
{% svg "/assets/icons/thumbs-up.svg" %}
```

```erb
<!-- ERB -->
<%= svg "/assets/icons/thumbs-up.svg" %>
```

in order to solve the problem, I put a `#` to scape the code.

```liquid
<!-- Liquid -->
{#% svg "/assets/icons/thumbs-up.svg" %}
```

```erb
<!-- ERB -->
<#%= svg "/assets/icons/thumbs-up.svg" %>
```
[reference article](https://juanvqz.github.io/bridgetownrb/2021/09/01/como-instalar-bridgetown-svg-inliner-en-bridgetownrb/)

**Comment by ayushn21** [comment]
Thanks for flagging this @JuanVqz. Not sure why this is happening but will investigate as soon as I can!

**Comment by ayushn21** [comment]
Hey @JuanVqz, I've tested this on Bridgetown 0.21.2 using Ruby 2.7.3 and 3.0.2 and been unable to reproduce the issue. The site is built without errors and renders as expected. Could you please post a test repo for me where I can reproduce and diagnose the error? Thanks :)

**Comment by JuanVqz** [comment]
sure! I'll do it this afternoon. I ran `bridgwtown --version` and returns `v0.21.3` "Broughton Beach" using ruby 3.0.0

**Comment by JuanVqz** [comment]
@ayushn21 when I got the error I just put both `liquid` and `erb` formats in the `markdown` file, so I didn't double check which one was the cause of the error I saw.

I tested it again and nothing failed now the `{% svg "images/github.svg" %}` is converted to a svg.

[here is the commit](https://github.com/JuanVqz/juanvqz.github.io/commit/e09eb28695423be2e5fee5c59d1b2ef4dbb0674d)

this is the [repo](https://github.com/JuanVqz/juanvqz.github.io) and this is the [post](http://localhost:4000/bridgetownrb/2021/09/01/como-instalar-bridgetown-svg-inliner-en-bridgetownrb/) where you can see it as `SVG tag`  instead of a liquid tag.

`erb` format is working as expected
 
 
![svg_liquid](https://user-images.githubusercontent.com/7331511/131925474-a248ea07-2a53-43f7-a025-1be5a46b756c.png)

**Comment by ayushn21** [comment]
Thanks @JuanVqz for the example repo. I'm not sure exactly what you're trying to accomplish but I hope the following answers your questions.

- You cannot use ERB and Liquid tags in the same file. You have to choose and specify your `template_engine` in the frontmatter.
- If you'd like to print out the Liquid or ERB tags themselves rather than "render" them, you need to escape those tags so the template engine doesn't render them and just displays them as-is. That is not within the scope of this library. Please see this StackOverflow post to for an example of how to escape Liquid tags: https://stackoverflow.com/questions/3426182/how-to-escape-liquid-template-tags.
- As an example, this will print out the raw Liquid tag as is instead of rendering it: `{{ "{% svg 'images/github.svg' " }}%}`.

Hope this helps!

**Comment by JuanVqz** [comment]
you are right I wanted to escape the liquid tags. thank you for your time
